HashTable:  Tabla.o main.o
				g++ main.o -o HashTable -std=c++11

Tabla.o:		Tabla.cpp
				g++ -c Tabla.cpp -o Tabla.o -std=c++11

main.o:		main.cpp
				g++ -c main.cpp -o main.o -std=c++11

clean:		  
				rm -rf *.o HashTable

				
