vector: main_vector.cpp vector.cpp vector.hpp common.hpp
	g++ -std=c++0x main_vector.cpp vector.cpp -o ../bin/vector

simplelinkedlist: main_simplelinkedlist.cpp node.cpp node.hpp simplelinkedlist.cpp simplelinkedlist.hpp common.hpp
	g++ -std=c++0x main_simplelinkedlist.cpp node.cpp simplelinkedlist.cpp -o ../bin/simplelinkedlist

stack: main_stack.cpp stack.cpp stack.hpp common.hpp
	g++ -std=c++0x main_stack.cpp stack.cpp -o ../bin/stack

queue: main_queue.cpp queue.cpp queue.hpp common.hpp
	g++ -std=c++0x main_queue.cpp queue.cpp -o ../bin/queue
