makefile: main_numero.cpp ../natural/natural.cpp ../entero/entero.cpp ../racional/racional.cpp ../real/real.cpp ../complejo/complejo.cpp
	g++ main_numero.cpp ../natural/natural.cpp ../entero/entero.cpp ../racional/racional.cpp ../real/real.cpp ../complejo/complejo.cpp
