AVL:  main_AVL.o
				g++ -w main_AVL.o -o ProgAVL -std=c++11

dni.o:		DNI.cpp
				g++ -c -w dni.cpp -o dni.o -std=c++11

main_AVL.o:		main_AVL.cpp
				g++ -c -w main_AVL.cpp -o main_AVL.o -std=c++11

clean:		  
				rm -rf *.o ProgAVL

				
