Ordenacion:  main_ordenacion.o
				g++ -w main_ordenacion.o -o ProgOrdenacion -std=c++11

dni.o:		DNI.cpp
				g++ -c -w dni.cpp -o dni.o -std=c++11

main_ordenacion.o:		main_ordenacion.cpp
				g++ -c -w main_ordenacion.cpp -o main_ordenacion.o -std=c++11

clean:		  
				rm -rf *.o ProgOrdenacion

				
