Ordenacion:  main_ABB.o
				g++ -w main_ABB.o -o ProgABB -std=c++11

dni.o:		DNI.cpp
				g++ -c -w dni.cpp -o dni.o -std=c++11

main_ABB.o:		main_ABB.cpp
				g++ -c -w main_ABB.cpp -o main_ABB.o -std=c++11

clean:		  
				rm -rf *.o ProgABB

				
